services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../../docker-volumes/postgres:/var/lib/postgresql/data:rw

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - 8001:8001
      - 6379:6379

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
