services:
  db:
    image: postgres:17
    container_name: covid-app-psql
    restart: unless-stopped
    env_file:
      - ../.env.development
    ports:
      - 5432:5432
    volumes:
      - ../../docker-volumes/postgres:/var/lib/postgresql/data:rw

  redis:
    image: redis/redis-stack:latest
    container_name: covid-app-redis
    restart: unless-stopped
    env_file:
      - ../.env.development
    ports:
      - 8001:8001
      - 6379:6379

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  api:
    build: ../../src/back-end
    container_name: covid-app-api
    env_file:
      - ../.env.development
    depends_on:
      - db
      - redis
    command: flask --app app --debug run --host=0.0.0.0
    # command: gunicorn -b 0.0.0.0:5555 --workers=2
    ports:
      - 5555:5555
    develop:
      watch:
        - action: sync
          path: ../../src/back-end/flaskr
          target: /usr/app/flasrk

  celery:
    build: ../../src/back-end
    container_name: covid-app-celery
    restart: always
    env_file:
      - ../.env.development
    depends_on:
      - db
      - redis
    command: celery -A app.celery_app worker --loglevel INFO
    develop:
      watch:
        - action: sync+restart
          path: ../../src/back-end/flaskr
          target: /usr/app/flasrk

  data-import:
    build: ../../src/back-end
    container_name: covid-app-data-import
    restart: no
    env_file:
      - ../.env.development
    volumes:
      - ../../covid-data:/usr/app/covid-data:ro
    depends_on:
      - db
      - redis
    command: python startup.py
    develop:
      watch:
        - action: sync+restart
          path: ../../src/back-end/flaskr
          target: /usr/app/flasrk
        - action: sync+restart
          path: ../../../covid-data:/usr/app/covid-data:ro
          target: /usr/app/covid-data
