/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChartIndexImport } from './routes/chart/index'
import { Route as TableIndexImport } from './routes/_table/index'

// Create/Update Routes

const ChartIndexRoute = ChartIndexImport.update({
  id: '/chart/',
  path: '/chart/',
  getParentRoute: () => rootRoute,
} as any)

const TableIndexRoute = TableIndexImport.update({
  id: '/_table/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_table/': {
      id: '/_table/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TableIndexImport
      parentRoute: typeof rootRoute
    }
    '/chart/': {
      id: '/chart/'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof TableIndexRoute
  '/chart': typeof ChartIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof TableIndexRoute
  '/chart': typeof ChartIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_table/': typeof TableIndexRoute
  '/chart/': typeof ChartIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chart'
  id: '__root__' | '/_table/' | '/chart/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TableIndexRoute: typeof TableIndexRoute
  ChartIndexRoute: typeof ChartIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  TableIndexRoute: TableIndexRoute,
  ChartIndexRoute: ChartIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_table/",
        "/chart/"
      ]
    },
    "/_table/": {
      "filePath": "_table/index.tsx"
    },
    "/chart/": {
      "filePath": "chart/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
